name: Francois Olwage
favicon: null
layout_spectrum: 0.8312256257049739
typography_spectrum: 0.06464481842704117
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d0e6fb'
    - '#2b6dc4'
    - '#050000'
    - '#73717e'
    - '#3f3d24'
  brandStrength: 0.6199191731866449
  lightness: 0.15416203392669559
  saturation: 0.667160167824477
  rhythmicContrast: 0.9378339634276927
purpose: []
